package wirebang

import "core:fmt"
import "core:math"
import "core:os"
import "core:path/filepath"
import "core:strings"

Emit_Options :: struct {
	package_name: string,
}

generate_code :: proc(patch: Patch, opts := Emit_Options{}, allocator := context.allocator) -> string {
	pkg := opts.package_name if opts.package_name != "" else "sfx"
	fn := sanitize_fn_name(patch.fn_name if patch.fn_name != "" else patch.name, context.temp_allocator)
	plan := plan_patch(patch, context.temp_allocator)
	defer destroy_plan(&plan)

	used := make(map[string]bool, context.temp_allocator)
	used["engine"] = true
	used["out"] = true
	used["sr"] = true
	used["frames"] = true
	names := make([]string, len(plan.nodes), context.temp_allocator)
	for n, i in plan.nodes {
		names[i] = var_name(n.node, &used, context.temp_allocator)
	}

	n := len(plan.nodes)
	inputs := make([][dynamic]int, n, context.temp_allocator)
	to_out := make([]bool, n, context.temp_allocator)
	for i in 0 ..< n {
		inputs[i] = make([dynamic]int, context.temp_allocator)
	}
	for e in plan.edges {
		if e.from < 0 || e.from >= n {
			continue
		}
		if e.to < 0 {
			to_out[e.from] = true
		} else if e.to < n {
			append(&inputs[e.to], e.from)
		}
	}

	need: Helper_Need
	uses_rand := false
	for node, i in plan.nodes {
		switch node.create.kind {
		case .Osc:
			need.osc = true
		case .Noise:
			need.noise = true
			uses_rand = true
		case .Filter:
			need.filter = true
		case .Gain:
			need.gain = true
		case .Shaper:
			need.shaper = true
		case .Panner:
			need.panner = true
		case .Delay:
			need.delay = true
		}
		if len(inputs[i]) >= 2 {
			need.mix = true
		}
		if to_out[i] {
			if node.create.kind == .Panner {
				need.add_stereo = true
			} else {
				need.add_mono = true
			}
		}
		for a in node.actions {
			if a.value.jitter > 0 {
				uses_rand = true
			}
		}
		if node.create.kind == .Panner {
			for j in 0 ..< n {
				for inp in inputs[j] {
					if inp == i && plan.nodes[j].create.kind != .Panner {
						need.downmix = true
					}
				}
			}
		}
	}

	b := strings.builder_make(allocator)
	fmt.sbprintf(&b, "// One-shot SFX generated by Wirebang. Yours to keep, copyright, and ship — no attribution required.\n")
	fmt.sbprintf(&b, "package %s\n\n", pkg)
	fmt.sbprintf(&b, "import \"core:math\"\n")
	if uses_rand {
		fmt.sbprintf(&b, "import \"core:math/rand\"\n")
	}
	fmt.sbprintf(&b, "import ma \"vendor:miniaudio\"\n\n")

	fmt.sbprintf(&b, "%s :: proc(engine: ^ma.engine) {{\n", fn)
	fmt.sbprintf(&b, "\tif engine == nil {{\n")
	fmt.sbprintf(&b, "\t\treturn\n")
	fmt.sbprintf(&b, "\t}}\n")
	fmt.sbprintf(&b, "\tsr := ma.engine_get_sample_rate(engine)\n")
	fmt.sbprintf(&b, "\tif sr == 0 {{\n")
	fmt.sbprintf(&b, "\t\tsr = %d\n", int(DEFAULT_SAMPLE_RATE))
	fmt.sbprintf(&b, "\t}}\n")
	dur := plan_duration(plan)
	fmt.sbprintf(&b, "\tframes := int(math.ceil_f64(f64(sr) * %s))\n", fmt_plain(dur))
	fmt.sbprintf(&b, "\tout := make([]f32, frames * 2)\n")
	fmt.sbprintf(&b, "\tdefer delete(out)\n")

	for node, i in plan.nodes {
		strings.write_string(&b, "\n")
		emit_node(&b, plan, names, inputs, i)
	}

	strings.write_string(&b, "\n")
	for i in 0 ..< n {
		if !to_out[i] {
			continue
		}
		if plan.nodes[i].create.kind == .Panner {
			fmt.sbprintf(&b, "\tadd_stereo(out, %s_buf)\n", names[i])
		} else {
			fmt.sbprintf(&b, "\tadd_mono_to_stereo(out, %s_buf)\n", names[i])
		}
	}
	fmt.sbprintf(&b, "\tsubmit_pcm(engine, out, sr)\n")
	fmt.sbprintf(&b, "}}\n")

	write_helpers(&b, need)
	return strings.to_string(b)
}

@(private)
is_panner :: proc(plan: Plan, i: int) -> bool {
	return i >= 0 && i < len(plan.nodes) && plan.nodes[i].create.kind == .Panner
}

@(private)
Node_Times :: struct {
	start, stop:     f32,
	freq0, freq1:    Num_Expr,
	peak:            Num_Expr,
	has_freq_ramp:   bool,
	curve:           Ramp_Curve,
	ramp_time:       f32,
}

@(private)
node_times :: proc(node: Planned_Node) -> Node_Times {
	t: Node_Times
	t.curve = .Exp
	for a in node.actions {
		switch a.kind {
		case .Set:
			if a.param == .Frequency {
				t.freq0 = a.value
			} else {
				t.peak = a.value
				t.start = a.time
			}
		case .Ramp:
			if a.param == .Frequency {
				t.freq1 = a.value
				t.has_freq_ramp = true
				t.ramp_time = a.time
				t.stop = a.time
				t.curve = a.curve
			} else {
				t.stop = a.time
			}
		case .Start:
			t.start = a.time
		case .Stop:
			t.stop = a.time
		}
	}
	return t
}

@(private)
emit_input :: proc(b: ^strings.Builder, plan: Plan, names: []string, inputs: [][dynamic]int, i: int) -> string {
	name := names[i]
	ins := inputs[i][:]
	if len(ins) == 0 {
		fmt.sbprintf(b, "\t%s_in := make([]f32, frames)\n", name)
		fmt.sbprintf(b, "\tdefer delete(%s_in)\n", name)
		return fmt.tprintf("%s_in", name)
	}
	if len(ins) == 1 {
		src := names[ins[0]]
		if is_panner(plan, ins[0]) {
			fmt.sbprintf(b, "\t%s_in := downmix(%s_buf, frames)\n", name, src)
			fmt.sbprintf(b, "\tdefer delete(%s_in)\n", name)
			return fmt.tprintf("%s_in", name)
		}
		return fmt.tprintf("%s_buf", src)
	}
	args := strings.builder_make(context.temp_allocator)
	for inp, k in ins {
		if k > 0 {
			strings.write_string(&args, ", ")
		}
		src := names[inp]
		if is_panner(plan, inp) {
			fmt.sbprintf(b, "\t%s_src_%d := downmix(%s_buf, frames)\n", name, k, src)
			fmt.sbprintf(b, "\tdefer delete(%s_src_%d)\n", name, k)
			fmt.sbprintf(&args, "%s_src_%d", name, k)
		} else {
			fmt.sbprintf(&args, "%s_buf", src)
		}
	}
	fmt.sbprintf(b, "\t%s_in := mix_mono(%s)\n", name, strings.to_string(args))
	fmt.sbprintf(b, "\tdefer delete(%s_in)\n", name)
	return fmt.tprintf("%s_in", name)
}

@(private)
ma_osc_token :: proc(t: Osc_Type) -> string {
	switch t {
	case .Sine:
		return ".sine"
	case .Square:
		return ".square"
	case .Sawtooth:
		return ".sawtooth"
	case .Triangle:
		return ".triangle"
	}
	return ".sine"
}

@(private)
ma_filter_token :: proc(t: Filter_Type) -> string {
	switch t {
	case .Lowpass:
		return ".lowpass"
	case .Highpass:
		return ".highpass"
	case .Bandpass:
		return ".bandpass"
	case .Notch:
		return ".notch"
	}
	return ".lowpass"
}

@(private)
ramp_token :: proc(c: Ramp_Curve) -> string {
	if c == .Lin {
		return ".lin"
	}
	return ".exp"
}

@(private)
emit_node :: proc(b: ^strings.Builder, plan: Plan, names: []string, inputs: [][dynamic]int, i: int) {
	node := plan.nodes[i]
	name := names[i]
	t := node_times(node)
	switch node.create.kind {
	case .Osc:
		fmt.sbprintf(b, "\t%s: ma.waveform\n", name)
		fmt.sbprintf(b, "\t%s_f0 := %s\n", name, emit_num_expr(t.freq0))
		f1_name := fmt.tprintf("%s_f0", name)
		if t.has_freq_ramp {
			fmt.sbprintf(b, "\t%s_f1 := %s\n", name, emit_num_expr(t.freq1))
			f1_name = fmt.tprintf("%s_f1", name)
		}
		fmt.sbprintf(
			b,
			"\t%s_cfg := ma.waveform_config_init(.f32, 1, sr, %s, 1, f64(%s_f0))\n",
			name,
			ma_osc_token(node.create.osc),
			name,
		)
		fmt.sbprintf(b, "\tif ma.waveform_init(&%s_cfg, &%s) != .SUCCESS {{\n", name, name)
		fmt.sbprintf(b, "\t\treturn\n")
		fmt.sbprintf(b, "\t}}\n")
		fmt.sbprintf(b, "\tdefer ma.waveform_uninit(&%s)\n", name)
		fmt.sbprintf(b, "\t%s_buf := make([]f32, frames)\n", name)
		fmt.sbprintf(b, "\tdefer delete(%s_buf)\n", name)
		fmt.sbprintf(
			b,
			"\tread_waveform_ramp(&%s, %s_buf, sr, %s_f0, %s, %s, %s, %s)\n",
			name,
			name,
			name,
			f1_name,
			fmt_f32(t.start),
			fmt_f32(t.stop),
			ramp_token(t.curve),
		)
	case .Noise:
		fmt.sbprintf(b, "\t%s: ma.noise\n", name)
		fmt.sbprintf(b, "\t%s_cfg := ma.noise_config_init(.f32, 1, .white, i32(rand.uint32()), 1)\n", name)
		fmt.sbprintf(b, "\tif ma.noise_init(&%s_cfg, nil, &%s) != .SUCCESS {{\n", name, name)
		fmt.sbprintf(b, "\t\treturn\n")
		fmt.sbprintf(b, "\t}}\n")
		fmt.sbprintf(b, "\tdefer ma.noise_uninit(&%s, nil)\n", name)
		fmt.sbprintf(b, "\t%s_buf := make([]f32, frames)\n", name)
		fmt.sbprintf(b, "\tdefer delete(%s_buf)\n", name)
		fmt.sbprintf(b, "\tread_noise_window(&%s, %s_buf, sr, %s, %s)\n", name, name, fmt_f32(t.start), fmt_f32(t.stop))
	case .Filter:
		in_expr := emit_input(b, plan, names, inputs, i)
		fmt.sbprintf(b, "\t%s: ma.biquad\n", name)
		fmt.sbprintf(b, "\t%s_f0 := %s\n", name, emit_num_expr(t.freq0))
		f1_name := fmt.tprintf("%s_f0", name)
		ramp_t := "0"
		if t.has_freq_ramp {
			fmt.sbprintf(b, "\t%s_f1 := %s\n", name, emit_num_expr(t.freq1))
			f1_name = fmt.tprintf("%s_f1", name)
			ramp_t = fmt_f32(t.ramp_time)
		}
		q := fmt_f32(node.create.q)
		kind := ma_filter_token(node.create.filter)
		fmt.sbprintf(b, "\tif !biquad_init_rbj(&%s, sr, %s, %s_f0, %s) {{\n", name, kind, name, q)
		fmt.sbprintf(b, "\t\treturn\n")
		fmt.sbprintf(b, "\t}}\n")
		fmt.sbprintf(b, "\tdefer ma.biquad_uninit(&%s, nil)\n", name)
		fmt.sbprintf(b, "\t%s_buf := make([]f32, frames)\n", name)
		fmt.sbprintf(b, "\tdefer delete(%s_buf)\n", name)
		fmt.sbprintf(
			b,
			"\tbiquad_sweep(&%s, %s, %s_buf, sr, %s, %s, %s_f0, %s, %s)\n",
			name,
			in_expr,
			name,
			kind,
			q,
			name,
			f1_name,
			ramp_t,
		)
	case .Gain:
		in_expr := emit_input(b, plan, names, inputs, i)
		fmt.sbprintf(b, "\t%s_peak := %s\n", name, emit_num_expr(t.peak))
		fmt.sbprintf(b, "\t%s_buf := make([]f32, frames)\n", name)
		fmt.sbprintf(b, "\tdefer delete(%s_buf)\n", name)
		fmt.sbprintf(b, "\tgain_env(%s, %s_buf, sr, %s_peak, %s, %s)\n", in_expr, name, name, fmt_f32(t.start), fmt_f32(t.stop))
	case .Shaper:
		in_expr := emit_input(b, plan, names, inputs, i)
		fmt.sbprintf(b, "\t%s_buf := make([]f32, frames)\n", name)
		fmt.sbprintf(b, "\tdefer delete(%s_buf)\n", name)
		fmt.sbprintf(b, "\twaveshape(%s, %s_buf, %s)\n", in_expr, name, fmt_f32(node.create.amount))
	case .Panner:
		in_expr := emit_input(b, plan, names, inputs, i)
		fmt.sbprintf(b, "\t%s_buf := make([]f32, frames * 2)\n", name)
		fmt.sbprintf(b, "\tdefer delete(%s_buf)\n", name)
		fmt.sbprintf(b, "\tpan_to_stereo(%s, %s_buf, %s)\n", in_expr, name, fmt_f32(node.create.pan))
	case .Delay:
		in_expr := emit_input(b, plan, names, inputs, i)
		fmt.sbprintf(b, "\t%s_buf := make([]f32, frames)\n", name)
		fmt.sbprintf(b, "\tdefer delete(%s_buf)\n", name)
		fmt.sbprintf(
			b,
			"\tdelay_line(%s, %s_buf, sr, %s, %s, %s)\n",
			in_expr,
			name,
			fmt_f32(node.create.time),
			fmt_f32(node.create.mix),
			fmt_f32(node.create.feedback),
		)
	}
}

@(private)
fmt_plain :: proc(v: f32) -> string {
	r := math.round(f64(v) * 1_000_000) / 1_000_000
	if r == 0 {
		return "0.0"
	}
	s := fmt.tprintf("%g", f32(r))
	if strings.contains(s, ".") || strings.contains(s, "e") || strings.contains(s, "E") {
		return s
	}
	return fmt.tprintf("%s.0", s)
}

@(private)
fmt_f32 :: proc(v: f32) -> string {
	r := math.round(f64(v) * 1_000_000) / 1_000_000
	if r == 0 {
		return "0"
	}
	s := fmt.tprintf("%g", f32(r))
	return fmt.tprintf("f32(%s)", s)
}

@(private)
emit_num_expr :: proc(expr: Num_Expr) -> string {
	inner: string
	if expr.jitter > 0 {
		inner = fmt.tprintf(
			"%s * (%s + rand.float32() * %s)",
			fmt_f32(expr.value),
			fmt_f32(1 - expr.jitter),
			fmt_f32(expr.jitter * 2),
		)
	} else {
		inner = fmt_f32(expr.value)
	}
	if expr.max_exp {
		return fmt.tprintf("max(f32(0.001), %s)", inner)
	}
	return inner
}

write_live_file :: proc(patch: Patch, dir: string) -> (path: string, ok: bool) {
	os.make_directory(dir)
	name := asset_file_name(patch, "odin", context.temp_allocator)
	path, _ = filepath.join({dir, name}, context.temp_allocator)
	src := generate_code(patch)
	defer delete(src)
	if err := os.write_entire_file(path, transmute([]u8)src); err != nil {
		return "", false
	}
	return strings.clone(path), true
}

write_baked_wav :: proc(patch: Patch, dir: string) -> (path: string, ok: bool) {
	os.make_directory(dir)
	wav_name := asset_file_name(patch, "wav", context.temp_allocator)
	path, _ = filepath.join({dir, wav_name}, context.temp_allocator)
	wav := bake_wav(patch)
	defer delete(wav)
	if err := os.write_entire_file(path, wav); err != nil {
		return "", false
	}
	return strings.clone(path), true
}
