// One-shot SFX generated by Wirebang. Yours to keep, copyright, and ship — no attribution required.
package sounds

import "core:math"
import "core:math/rand"
import ma "vendor:miniaudio"

play_thump :: proc(engine: ^ma.engine) {
	if engine == nil {
		return
	}
	sr := ma.engine_get_sample_rate(engine)
	if sr == 0 {
		sr = 48000
	}
	frames := int(math.ceil_f64(f64(sr) * 0.14))
	out := make([]f32, frames * 2)
	defer delete(out)

	body: ma.waveform
	body_f0 := f32(90) * (f32(0.95) + rand.float32() * f32(0.1))
	body_f1 := max(f32(0.001), f32(38) * (f32(0.95) + rand.float32() * f32(0.1)))
	body_cfg := ma.waveform_config_init(.f32, 1, sr, .sine, 1, f64(body_f0))
	if ma.waveform_init(&body_cfg, &body) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&body)
	body_buf := make([]f32, frames)
	defer delete(body_buf)
	read_waveform_ramp(&body, body_buf, sr, body_f0, body_f1, 0, f32(0.12), .exp)

	click: ma.waveform
	click_f0 := f32(420) * (f32(0.9) + rand.float32() * f32(0.2))
	click_f1 := max(f32(0.001), f32(120) * (f32(0.9) + rand.float32() * f32(0.2)))
	click_cfg := ma.waveform_config_init(.f32, 1, sr, .triangle, 1, f64(click_f0))
	if ma.waveform_init(&click_cfg, &click) != .SUCCESS {
		return
	}
	defer ma.waveform_uninit(&click)
	click_buf := make([]f32, frames)
	defer delete(click_buf)
	read_waveform_ramp(&click, click_buf, sr, click_f0, click_f1, 0, f32(0.018), .exp)

	amp_peak := max(f32(0.001), f32(0.28) * (f32(0.96) + rand.float32() * f32(0.08)))
	amp_buf := make([]f32, frames)
	defer delete(amp_buf)
	gain_env(body_buf, amp_buf, sr, amp_peak, 0, f32(0.12))

	clickAmp_peak := max(f32(0.001), f32(0.08) * (f32(0.9) + rand.float32() * f32(0.2)))
	clickAmp_buf := make([]f32, frames)
	defer delete(clickAmp_buf)
	gain_env(click_buf, clickAmp_buf, sr, clickAmp_peak, 0, f32(0.018))

	add_mono_to_stereo(out, amp_buf)
	add_mono_to_stereo(out, clickAmp_buf)
	submit_pcm(engine, out, sr)
}


@(private="file")
Ramp :: enum {
	lin,
	exp,
}

@(private="file")
read_waveform_ramp :: proc(w: ^ma.waveform, out: []f32, sr: u32, f0, f1, start, stop: f32, curve: Ramp) {
	n := len(out)
	i0 := clamp(int(start * f32(sr)), 0, n)
	i1 := clamp(int(stop * f32(sr)), 0, n)
	if i1 <= i0 {
		return
	}
	span := stop - start
	if f0 == f1 || span <= 0 {
		ma.waveform_set_frequency(w, f64(f0))
		ma.waveform_read_pcm_frames(w, raw_data(out[i0:i1]), u64(i1 - i0), nil)
		return
	}
	for i in i0 ..< i1 {
		x := (f32(i) / f32(sr) - start) / span
		f: f32
		if curve == .exp {
			a := max(f0, 0.001)
			b := max(f1, 0.001)
			f = a * math.pow(b / a, x)
		} else {
			f = f0 + (f1 - f0) * x
		}
		ma.waveform_set_frequency(w, f64(f))
		ma.waveform_read_pcm_frames(w, &out[i], 1, nil)
	}
}

@(private="file")
gain_env :: proc(in_buf, out_buf: []f32, sr: u32, peak, start, stop: f32) {
	n := min(len(in_buf), len(out_buf))
	span := stop - start
	for i in 0 ..< n {
		t := f32(i) / f32(sr)
		g: f32 = 0
		if t >= start && t < stop && span > 0 {
			x := (t - start) / span
			a := max(peak, 0.001)
			g = a * math.pow(f32(0.001) / a, x)
		}
		out_buf[i] = in_buf[i] * g
	}
}

@(private="file")
add_mono_to_stereo :: proc(out, mono: []f32) {
	n := min(len(mono), len(out) / 2)
	for i in 0 ..< n {
		out[i * 2] += mono[i]
		out[i * 2 + 1] += mono[i]
	}
}

@(private="file")
MAX_PLAYING :: 8

@(private="file")
Playing :: struct {
	used:   bool,
	buffer: ma.audio_buffer,
	sound:  ma.sound,
}

@(private="file")
g_playing: [MAX_PLAYING]Playing

@(private="file")
reap_playing :: proc() {
	for &slot in g_playing {
		if slot.used && bool(ma.sound_at_end(&slot.sound)) {
			ma.sound_uninit(&slot.sound)
			ma.audio_buffer_uninit(&slot.buffer)
			slot.used = false
		}
	}
}

@(private="file")
submit_pcm :: proc(engine: ^ma.engine, frames: []f32, sr: u32) {
	if engine == nil || len(frames) < 2 {
		return
	}
	reap_playing()
	slot: ^Playing
	for &s in g_playing {
		if !s.used {
			slot = &s
			break
		}
	}
	if slot == nil {
		slot = &g_playing[0]
		ma.sound_uninit(&slot.sound)
		ma.audio_buffer_uninit(&slot.buffer)
		slot.used = false
	}
	nframes := u64(len(frames) / 2)
	cfg := ma.audio_buffer_config_init(.f32, 2, nframes, raw_data(frames), nil)
	cfg.sampleRate = sr
	if ma.audio_buffer_init_copy(&cfg, &slot.buffer) != .SUCCESS {
		return
	}
	flags := ma.sound_flags{.NO_PITCH, .NO_SPATIALIZATION}
	if ma.sound_init_from_data_source(engine, cast(^ma.data_source)&slot.buffer, flags, nil, &slot.sound) != .SUCCESS {
		ma.audio_buffer_uninit(&slot.buffer)
		return
	}
	if ma.sound_start(&slot.sound) != .SUCCESS {
		ma.sound_uninit(&slot.sound)
		ma.audio_buffer_uninit(&slot.buffer)
		return
	}
	slot.used = true
}
